name: laboratorio
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.17
  logger: ^2.5.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/reset_icon.svg
    - assets/icons/tap_icon.svg
    - assets/icons/minus_icon.svg

  fonts:
    - family: National Park
      fonts:
        - asset: assets/fonts/NationalPark-Bold.ttf

